# fly.toml app configuration file generated for liftskit-backend on 2025-09-14T00:03:21-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'liftskit-backend'
primary_region = 'sjc'
kill_signal = 'SIGTERM'

[build]

[deploy]
  # release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'liftskit-backend.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
